### PR TITLE
Add filename param to Translator#translate_document() method

### PR DESCRIPTION
**Pull request by seratch**
Thanks for making this great SDK!

When using `Translator#translate_document()` method with BinaryIO `input_document` argument, the internal `translate_document_upload` call fails due to the following exception:

```
  File "/path-to-ptyhon/lib/python3.9/site-packages/deepl/translator.py", line 827, in translate_document
    handle = self.translate_document_upload(
  File "/path-to-ptyhon/lib/python3.9/site-packages/deepl/translator.py", line 892, in translate_document_upload
    raise ValueError(
ValueError: filename is required if uploading file content as string or bytes
```

This pull request resolves this issue by adding a new `filename` argument to `translate_document()` method.

### CODE REVIEW

**Comment by daniel-jones-deepl** [comment]
Hi @seratch, thank you for finding this mistake. I have to check whether we're able to accept this Pull Request.

**Comment by daniel-jones-deepl** [comment]
I'd just like to mention a workaround: (although you have probably already figured this out)
You can use `translate_document_upload` directly - this function is public and we will maintain backward compatibility for it.

**Comment by seratch** [comment]
@daniel-jones-deepl Thanks for your response! Yes, I went with the workaround: https://github.com/seratch/deepl-document-translator-for-slack/blob/b5a62d1260b91786dd7aa8d669a4a713da4127c1/app.py#L189-L252

**Comment by seratch** [comment]
@daniel-jones-deepl I've resolved the conflicts. Can you check it again if you are still interested in the change here? If not, please feel free to close this PR 👋

**Comment by daniel-jones-deepl** [comment]
Hi @seratch, thanks for resolving the conflicts. Yes we want to accept this change, we are working out issues surrounding accepting contributions.

**Comment by seratch** [comment]
@daniel-jones-deepl Thanks, I don’t have any issues withe the license 👍

**Comment by daniel-jones-deepl** [comment]
Thank you 😄 . I'll publish a new version in a moment.

**Pull request merged**
